[project]
name = "langchain-for-ai-agent"
version = "0.1.0"
description = "LangChain AI Agent with LangGraph"
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.2.8",
    "langgraph>=1.0.7",
    "langchain-google-genai>=4.2.0",
    "python-dotenv>=1.2.1",
]
